version: 2.1
orbs:
  node: circleci/node@4.5.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '14.17.5'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn install
      - run:
          command: yarn jest
workflows:
    build-and-test:
      jobs:
        - build-and-test